<?php
/**
 * @package     Joomla.Site
 * @subpackage  mod_custom
 *
 * @copyright   (C) 2009 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Uri\Uri;

$modId = 'mod-custom' . $module->id;

if ($params->get('backgroundimage'))
{
	/** @var Joomla\CMS\WebAsset\WebAssetManager $wa */
	$wa = Factory::getApplication()->getDocument()->getWebAssetManager();
	$wa->addInlineStyle('
#' . $modId . '{background-image: url("' . Uri::root(true) . '/' . HTMLHelper::_('cleanImageURL', $params->get('backgroundimage'))->url . '");}
', ['name' => $modId]);
}

?>

<div id="<?php echo $modId; ?>" class="mod-custom custom">
	<?php echo $module->content; ?>
<div class="uk-divider" uk-grid>
    <div class="uk-width-small@m">
        <ul class="uk-nav uk-nav-default" uk-switcher="connect: #component-nav; animation: uk-animation-fade">
            <li><a href="#">Активный</a></li>
            <li><a href="#">Элемент</a></li>
            <li><a href="#">Навигация</a></li>
            <li><a href="#">Активный</a></li>
            <li><a href="#">Элемент</a></li>
            <li><a href="#">Навигация</a></li>			
        </ul>
    </div>
    <div class="uk-width-expand@m">
        <ul id="component-nav" class="uk-switcher">
            <li><iframe width="560" height="315" src="https://www.youtube.com/embed/_hofvjyOdrI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></li>
            <li><iframe src="https://www.facebook.com/plugins/video.php?height=314&href=https%3A%2F%2Fwww.facebook.com%2FBestnewskz%2Fvideos%2F185269864324222%2F&show_text=false&width=560&t=0" width="560" height="314" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share" allowFullScreen="true"></iframe></li>
            <li><iframe width="560" height="315" src="https://www.youtube.com/embed/_hofvjyOdrI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></li>
            <li><iframe src="https://www.facebook.com/plugins/video.php?height=314&href=https%3A%2F%2Fwww.facebook.com%2FBestnewskz%2Fvideos%2F185269864324222%2F&show_text=false&width=560&t=0" width="560" height="314" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share" allowFullScreen="true"></iframe></li>
            <li><iframe width="560" height="315" src="https://www.youtube.com/embed/_hofvjyOdrI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></li>
            <li><iframe src="https://www.facebook.com/plugins/video.php?height=314&href=https%3A%2F%2Fwww.facebook.com%2FBestnewskz%2Fvideos%2F185269864324222%2F&show_text=false&width=560&t=0" width="560" height="314" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowfullscreen="true" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share" allowFullScreen="true"></iframe></li>
        </ul>
    </div>
</div>
<hr>
<div uk-grid>
    <div class="uk-width-small@m">
        <ul class="uk-nav uk-nav-default" uk-switcher="connect: #component-nav1; animation: uk-animation-fade">
            <li><a href="#">Активный</a></li>
            <li><a href="#">Элемент</a></li>
            <li><a href="#">Навигация</a></li>
            <li><a href="#">Активный</a></li>
            <li><a href="#">Элемент</a></li>
            <li><a href="#">Навигация</a></li>			
        </ul>
    </div>
    <div class="uk-width-expand@m">
        <ul id="component-nav1" class="uk-switcher">
            <li><blockquote class="tiktok-embed" cite="https://www.tiktok.com/@bestnews.kz1/video/7224341985547603205" data-video-id="7224341985547603205" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@bestnews.kz1" href="https://www.tiktok.com/@bestnews.kz1?refer=embed">@bestnews.kz1</a> Ринат Зайытов: “Мен 2019 жылдан бері адам баласына сенбеймін” <a title="ринатзайытов" target="_blank" href="https://www.tiktok.com/tag/%D1%80%D0%B8%D0%BD%D0%B0%D1%82%D0%B7%D0%B0%D0%B9%D1%8B%D1%82%D0%BE%D0%B2?refer=embed">#ринатзайытов</a> <a title="мажилис" target="_blank" href="https://www.tiktok.com/tag/%D0%BC%D0%B0%D0%B6%D0%B8%D0%BB%D0%B8%D1%81?refer=embed">#мажилис</a> <a title="айтыс" target="_blank" href="https://www.tiktok.com/tag/%D0%B0%D0%B9%D1%82%D1%8B%D1%81?refer=embed">#айтыс</a> <a title="казахстан🇰🇿" target="_blank" href="https://www.tiktok.com/tag/%D0%BA%D0%B0%D0%B7%D0%B0%D1%85%D1%81%D1%82%D0%B0%D0%BD%F0%9F%87%B0%F0%9F%87%BF?refer=embed">#казахстан🇰🇿</a> <a title="депутат" target="_blank" href="https://www.tiktok.com/tag/%D0%B4%D0%B5%D0%BF%D1%83%D1%82%D0%B0%D1%82?refer=embed">#депутат</a> <a title="хочуврек" target="_blank" href="https://www.tiktok.com/tag/%D1%85%D0%BE%D1%87%D1%83%D0%B2%D1%80%D0%B5%D0%BA?refer=embed">#хочуврек</a> <a title="подпишись" target="_blank" href="https://www.tiktok.com/tag/%D0%BF%D0%BE%D0%B4%D0%BF%D0%B8%D1%88%D0%B8%D1%81%D1%8C?refer=embed">#подпишись</a> <a title="хочу20кподписчиков❤️" target="_blank" href="https://www.tiktok.com/tag/%D1%85%D0%BE%D1%87%D1%8320%D0%BA%D0%BF%D0%BE%D0%B4%D0%BF%D0%B8%D1%81%D1%87%D0%B8%D0%BA%D0%BE%D0%B2%E2%9D%A4%EF%B8%8F?refer=embed">#хочу20кподписчиков❤️</a> <a target="_blank" title="♬ оригинальный звук - Bestnews.kz1" href="https://www.tiktok.com/music/оригинальный-звук-7224341984223546117?refer=embed">♬ оригинальный звук - Bestnews.kz1</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script></li>
            <li><blockquote class="tiktok-embed" cite="https://www.tiktok.com/@bestnews.kz1/video/7225856599254912261" data-video-id="7225856599254912261" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@bestnews.kz1" href="https://www.tiktok.com/@bestnews.kz1?refer=embed">@bestnews.kz1</a> Казахстанцев обещают защитить о покупки смартфонлв с повторяющимися IMEI-кодами <a title="казахстан🇰🇿" target="_blank" href="https://www.tiktok.com/tag/%D0%BA%D0%B0%D0%B7%D0%B0%D1%85%D1%81%D1%82%D0%B0%D0%BD%F0%9F%87%B0%F0%9F%87%BF?refer=embed">#казахстан🇰🇿</a> <a title="багдатмусин" target="_blank" href="https://www.tiktok.com/tag/%D0%B1%D0%B0%D0%B3%D0%B4%D0%B0%D1%82%D0%BC%D1%83%D1%81%D0%B8%D0%BD?refer=embed">#багдатмусин</a> <a title="imei" target="_blank" href="https://www.tiktok.com/tag/imei?refer=embed">#imei</a> <a title="iphone" target="_blank" href="https://www.tiktok.com/tag/iphone?refer=embed">#iphone</a> <a title="контрабанда" target="_blank" href="https://www.tiktok.com/tag/%D0%BA%D0%BE%D0%BD%D1%82%D1%80%D0%B0%D0%B1%D0%B0%D0%BD%D0%B4%D0%B0?refer=embed">#контрабанда</a> <a title="хочуврек" target="_blank" href="https://www.tiktok.com/tag/%D1%85%D0%BE%D1%87%D1%83%D0%B2%D1%80%D0%B5%D0%BA?refer=embed">#хочуврек</a> <a title="подпишисьпж" target="_blank" href="https://www.tiktok.com/tag/%D0%BF%D0%BE%D0%B4%D0%BF%D0%B8%D1%88%D0%B8%D1%81%D1%8C%D0%BF%D0%B6?refer=embed">#подпишисьпж</a> <a target="_blank" title="♬ оригинальный звук - Bestnews.kz1" href="https://www.tiktok.com/music/оригинальный-звук-7225856613477829381?refer=embed">♬ оригинальный звук - Bestnews.kz1</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script></li>
            <li><blockquote class="tiktok-embed" cite="https://www.tiktok.com/@bestnews.kz1/video/7223755829000899845" data-video-id="7223755829000899845" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@bestnews.kz1" href="https://www.tiktok.com/@bestnews.kz1?refer=embed">@bestnews.kz1</a> Нужна ли в Казахстане полиция для животных? <a title="хочуврек" target="_blank" href="https://www.tiktok.com/tag/%D1%85%D0%BE%D1%87%D1%83%D0%B2%D1%80%D0%B5%D0%BA?refer=embed">#хочуврек</a> <a title="хочу20кподписчиков❤️" target="_blank" href="https://www.tiktok.com/tag/%D1%85%D0%BE%D1%87%D1%8320%D0%BA%D0%BF%D0%BE%D0%B4%D0%BF%D0%B8%D1%81%D1%87%D0%B8%D0%BA%D0%BE%D0%B2%E2%9D%A4%EF%B8%8F?refer=embed">#хочу20кподписчиков❤️</a> <a title="казахстан" target="_blank" href="https://www.tiktok.com/tag/%D0%BA%D0%B0%D0%B7%D0%B0%D1%85%D1%81%D1%82%D0%B0%D0%BD?refer=embed">#казахстан</a> <a title="животные" target="_blank" href="https://www.tiktok.com/tag/%D0%B6%D0%B8%D0%B2%D0%BE%D1%82%D0%BD%D1%8B%D0%B5?refer=embed">#животные</a> <a title="зульфиясулейменова" target="_blank" href="https://www.tiktok.com/tag/%D0%B7%D1%83%D0%BB%D1%8C%D1%84%D0%B8%D1%8F%D1%81%D1%83%D0%BB%D0%B5%D0%B9%D0%BC%D0%B5%D0%BD%D0%BE%D0%B2%D0%B0?refer=embed">#зульфиясулейменова</a> <a title="полиция" target="_blank" href="https://www.tiktok.com/tag/%D0%BF%D0%BE%D0%BB%D0%B8%D1%86%D0%B8%D1%8F?refer=embed">#полиция</a> <a title="бродячиепсы" target="_blank" href="https://www.tiktok.com/tag/%D0%B1%D1%80%D0%BE%D0%B4%D1%8F%D1%87%D0%B8%D0%B5%D0%BF%D1%81%D1%8B?refer=embed">#бродячиепсы</a> <a title="подпишись🙏" target="_blank" href="https://www.tiktok.com/tag/%D0%BF%D0%BE%D0%B4%D0%BF%D0%B8%D1%88%D0%B8%D1%81%D1%8C%F0%9F%99%8F?refer=embed">#подпишись🙏</a> <a target="_blank" title="♬ оригинальный звук - Bestnews.kz1" href="https://www.tiktok.com/music/оригинальный-звук-7223755809057819398?refer=embed">♬ оригинальный звук - Bestnews.kz1</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script></li>
            <li><blockquote class="tiktok-embed" cite="https://www.tiktok.com/@bestnews.kz1/video/7223723134262807814" data-video-id="7223723134262807814" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@bestnews.kz1" href="https://www.tiktok.com/@bestnews.kz1?refer=embed">@bestnews.kz1</a> Когда в Астане запустят 5G <a title="астана" target="_blank" href="https://www.tiktok.com/tag/%D0%B0%D1%81%D1%82%D0%B0%D0%BD%D0%B0?refer=embed">#астана</a> <a title="5g" target="_blank" href="https://www.tiktok.com/tag/5g?refer=embed">#5g</a> <a title="багдатмусин" target="_blank" href="https://www.tiktok.com/tag/%D0%B1%D0%B0%D0%B3%D0%B4%D0%B0%D1%82%D0%BC%D1%83%D1%81%D0%B8%D0%BD?refer=embed">#багдатмусин</a> <a title="интернет" target="_blank" href="https://www.tiktok.com/tag/%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D0%BD%D0%B5%D1%82?refer=embed">#интернет</a> <a title="хочуврек" target="_blank" href="https://www.tiktok.com/tag/%D1%85%D0%BE%D1%87%D1%83%D0%B2%D1%80%D0%B5%D0%BA?refer=embed">#хочуврек</a> <a title="хочу20кподписчиков❤️" target="_blank" href="https://www.tiktok.com/tag/%D1%85%D0%BE%D1%87%D1%8320%D0%BA%D0%BF%D0%BE%D0%B4%D0%BF%D0%B8%D1%81%D1%87%D0%B8%D0%BA%D0%BE%D0%B2%E2%9D%A4%EF%B8%8F?refer=embed">#хочу20кподписчиков❤️</a> <a title="казахстан" target="_blank" href="https://www.tiktok.com/tag/%D0%BA%D0%B0%D0%B7%D0%B0%D1%85%D1%81%D1%82%D0%B0%D0%BD?refer=embed">#казахстан</a> <a title="антенны5g" target="_blank" href="https://www.tiktok.com/tag/%D0%B0%D0%BD%D1%82%D0%B5%D0%BD%D0%BD%D1%8B5g?refer=embed">#антенны5g</a> <a target="_blank" title="♬ оригинальный звук - Bestnews.kz1" href="https://www.tiktok.com/music/оригинальный-звук-7223723156631407365?refer=embed">♬ оригинальный звук - Bestnews.kz1</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script></li>
            <li><blockquote class="tiktok-embed" cite="https://www.tiktok.com/@bestnews.kz1/video/7222966256717090053" data-video-id="7222966256717090053" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@bestnews.kz1" href="https://www.tiktok.com/@bestnews.kz1?refer=embed">@bestnews.kz1</a> Астана «утонула» в сугробах <a title="астана" target="_blank" href="https://www.tiktok.com/tag/%D0%B0%D1%81%D1%82%D0%B0%D0%BD%D0%B0?refer=embed">#астана</a> <a title="сугробы" target="_blank" href="https://www.tiktok.com/tag/%D1%81%D1%83%D0%B3%D1%80%D0%BE%D0%B1%D1%8B?refer=embed">#сугробы</a> <a title="казахстан" target="_blank" href="https://www.tiktok.com/tag/%D0%BA%D0%B0%D0%B7%D0%B0%D1%85%D1%81%D1%82%D0%B0%D0%BD?refer=embed">#казахстан</a> <a title="лыжи" target="_blank" href="https://www.tiktok.com/tag/%D0%BB%D1%8B%D0%B6%D0%B8?refer=embed">#лыжи</a> <a title="хочуврек" target="_blank" href="https://www.tiktok.com/tag/%D1%85%D0%BE%D1%87%D1%83%D0%B2%D1%80%D0%B5%D0%BA?refer=embed">#хочуврек</a> <a title="хочу20кподписчиков❤️" target="_blank" href="https://www.tiktok.com/tag/%D1%85%D0%BE%D1%87%D1%8320%D0%BA%D0%BF%D0%BE%D0%B4%D0%BF%D0%B8%D1%81%D1%87%D0%B8%D0%BA%D0%BE%D0%B2%E2%9D%A4%EF%B8%8F?refer=embed">#хочу20кподписчиков❤️</a> <a title="уборкаснега" target="_blank" href="https://www.tiktok.com/tag/%D1%83%D0%B1%D0%BE%D1%80%D0%BA%D0%B0%D1%81%D0%BD%D0%B5%D0%B3%D0%B0?refer=embed">#уборкаснега</a> <a target="_blank" title="♬ оригинальный звук - Bestnews.kz1" href="https://www.tiktok.com/music/оригинальный-звук-7222966262148664070?refer=embed">♬ оригинальный звук - Bestnews.kz1</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script></li>
            <li><blockquote class="tiktok-embed" cite="https://www.tiktok.com/@bestnews.kz1/video/7222964117009714437" data-video-id="7222964117009714437" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@bestnews.kz1" href="https://www.tiktok.com/@bestnews.kz1?refer=embed">@bestnews.kz1</a> Экс-министр культуры и спорта РК Арыстанбек Мухамедиулы сделал громкое заявление в суде полностью» <a title="музей" target="_blank" href="https://www.tiktok.com/tag/%D0%BC%D1%83%D0%B7%D0%B5%D0%B9?refer=embed">#музей</a> <a title="арыстанбекмухамедиулы" target="_blank" href="https://www.tiktok.com/tag/%D0%B0%D1%80%D1%8B%D1%81%D1%82%D0%B0%D0%BD%D0%B1%D0%B5%D0%BA%D0%BC%D1%83%D1%85%D0%B0%D0%BC%D0%B5%D0%B4%D0%B8%D1%83%D0%BB%D1%8B?refer=embed">#арыстанбекмухамедиулы</a> <a title="суды" target="_blank" href="https://www.tiktok.com/tag/%D1%81%D1%83%D0%B4%D1%8B?refer=embed">#суды</a> <a title="казахстан" target="_blank" href="https://www.tiktok.com/tag/%D0%BA%D0%B0%D0%B7%D0%B0%D1%85%D1%81%D1%82%D0%B0%D0%BD?refer=embed">#казахстан</a> <a title="золотойчеловек" target="_blank" href="https://www.tiktok.com/tag/%D0%B7%D0%BE%D0%BB%D0%BE%D1%82%D0%BE%D0%B9%D1%87%D0%B5%D0%BB%D0%BE%D0%B2%D0%B5%D0%BA?refer=embed">#золотойчеловек</a> <a title="хочуврек" target="_blank" href="https://www.tiktok.com/tag/%D1%85%D0%BE%D1%87%D1%83%D0%B2%D1%80%D0%B5%D0%BA?refer=embed">#хочуврек</a> <a title="хочу20к" target="_blank" href="https://www.tiktok.com/tag/%D1%85%D0%BE%D1%87%D1%8320%D0%BA?refer=embed">#хочу20к</a> <a target="_blank" title="♬ оригинальный звук - Bestnews.kz1" href="https://www.tiktok.com/music/оригинальный-звук-7222964116873186053?refer=embed">♬ оригинальный звук - Bestnews.kz1</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script></li>
        </ul>
    </div>
</div>
</div>
