<?php

/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   (C) 2006 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

\defined('_JEXEC') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Language\Associations;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Layout\FileLayout;
use Joomla\CMS\Layout\LayoutHelper;
use Joomla\CMS\Router\Route;
use Joomla\CMS\Uri\Uri;
use Joomla\Component\Content\Administrator\Extension\ContentComponent;
use Joomla\Component\Content\Site\Helper\RouteHelper;



$app = Factory::getContainer()->get(Joomla\CMS\Application\SiteApplication::class);

// Create a shortcut for params.
$params  = $this->item->params;
$canEdit = $this->item->params->get('access-edit');
$info    = $params->get('info_block_position', 0);

// Check if associations are implemented. If they are, define the parameter.
$assocParam = (Associations::isEnabled() && $params->get('show_associations'));

$currentDate   = Factory::getDate()->format(Text::_('DATE_FORMAT_LC6'));
$isUnpublished = ($this->item->state == ContentComponent::CONDITION_UNPUBLISHED || $this->item->publish_up > $currentDate)
    || ($this->item->publish_down < $currentDate && $this->item->publish_down !== null);

?>
<a href="#i-<?php echo $this->item->id; ?>" class="uk-link-heading" uk-toggle=""> 
<?php echo LayoutHelper::render('joomla.content.intro_personal', $this->item); ?>

<div class="item-content uk-card-body uk-card-small  uk-padding-remove-top">
    <?php if ($isUnpublished) { ?>
        <div class="system-unpublished">
        <?php
    }

    echo LayoutHelper::render('joomla.content.blog_style_default_item_title', $this->item);

    if ($canEdit) {
        echo LayoutHelper::render('joomla.content.icons', array('params' => $params, 'item' => $this->item));
    }

    // @todo Not that elegant would be nice to group the params
    $useDefList = ($params->get('show_modify_date') || $params->get('show_publish_date')
        || $params->get('show_create_date') || $params->get('show_hits')
        || $params->get('show_category') || $params->get('show_parent_category')
        || $params->get('show_author') || $assocParam);

    if ($useDefList && ($info == 0 || $info == 2)) {
        echo LayoutHelper::render('joomla.content.info_block', array('item' => $this->item, 'params' => $params, 'position' => 'above'));
    }
    if ($info == 0 && $params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) {
        echo LayoutHelper::render('joomla.content.tags', $this->item->tags->itemTags);
    }

    if (!$params->get('show_intro')) {
        // Content is generated by content plugin event "onContentAfterTitle"
        echo $this->item->event->afterDisplayTitle;
    }

    // Content is generated by content plugin event "onContentBeforeDisplay"
    echo $this->item->event->beforeDisplayContent;
 

    if ($useDefList && $info == 1) {
        echo LayoutHelper::render('joomla.content.info_block', array('item' => $this->item, 'params' => $params, 'position' => 'below'));
    }

    if (($info == 1 || $info == 2) && $params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) {
        echo LayoutHelper::render('joomla.content.tags', $this->item->tags->itemTags);
    }

    if ($params->get('show_readmore') && $this->item->readmore) {
        if ($params->get('access-view')) {
            $link = Route::_(RouteHelper::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language));
        } else {
            $menu = $app->getMenu();
            $active = $menu->getActive();
            $itemId = $active->id;
            $link = new Uri(Route::_('index.php?option=com_users&view=login&Itemid=' . $itemId, false));
            $link->setVar('return', base64_encode(RouteHelper::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language)));
        }

        echo LayoutHelper::render('joomla.content.readmore', array('item' => $this->item, 'params' => $params, 'link' => $link));
    }
       
 
	
    if ($isUnpublished) {
        echo '</div>';
    }

    // Content is generated by content plugin event "onContentAfterDisplay"
    echo $this->item->event->afterDisplayContent;

    ?>
</div>
</a>
			<div id="i-<?php echo $this->item->id; ?>" uk-modal="">
				<div class="uk-modal-dialog">
					<button type="button" class="uk-modal-close-default uk-light" uk-close=""></button>
					<div class="uk-modal-header uk-background-primary uk-text-center uk-light ">
						<h4 class="uk-modal-title uk-text-lead " ><?php echo $this -> escape($this -> item -> title); ?></h4></div>
						<div class="uk-modal-body uk-box-shadow-xlarge uk-box-shadow-hover-medium" uk-overflow-auto="">
					<div class="uk-flex uk-flex-center uk-margin-bottom"><?php echo LayoutHelper::render( 'joomla.content.full_personal', $this->item );?></div>
						<?php echo $this->item->text;

if ( $canEdit || $params->get( 'show_print_icon' ) || $params->get( 'show_email_icon' ) )
{
    echo LayoutHelper::render( 'joomla.content.icons', [ 'params' => $params, 'item' => $this->item, 'print' => false ] );
}
 echo $this->item->event->beforeDisplayContent;
    if (isset($urls) && ((!empty($urls->urls_position) && ($urls->urls_position == '0')) || ($params->get('urls_position') == '0' && empty($urls->urls_position))) || (empty($urls->urls_position) && (!$params->get('urls_position')))) {
        echo $this->loadTemplate('links');
    }

// Todo Not that elegant would be nice to group the params
$useDefList = ( $params->get( 'show_modify_date' ) || $params->get( 'show_publish_date' ) || $params->get( 'show_create_date' ) || $params->get( 'show_hits' ) || $params->get( 'show_category' ) || $params->get( 'show_parent_category' ) || $params->get( 'show_author' ) || $assocParam );

if ( $useDefList && ( $info == 0 || $info == 2 ) )
{
    echo '<div class="uk-article-meta">';

    // Todo: for Joomla4 joomla.content.info_block.block can be changed to joomla.content.info_block
    echo LayoutHelper::render( 'joomla.content.info_block', [ 'item' => $this->item, 'params' => $params, 'position' => 'above' ] );

    if ( $info == 0 && $params->get( 'show_tags', 1 ) && !empty( $this->item->tags->itemTags ) )
    {
        echo LayoutHelper::render( 'joomla.content.tags', $this->item->tags->itemTags );
    }

    echo '</div>';
}



						?>
						
					</div>
					<div class="uk-modal-footer uk-text-right uk-background-body-2 box-shadow-footer">						
						<button type="button" class="uk-button uk-button-primary uk-modal-close uk-button-small"><?= JText::_('JLIB_HTML_BEHAVIOR_CLOSE') ?></button>
					</div>
				</div>
			</div>